### ISSUE TITLE
Choropleth: Legend vanishes if another layer selected and unselected

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM_APP_stemp_abw#14]
Try this:
1. Select a choropleth layer -> layer and legend is shown
2. Select another choropleth layer -> layer is shown (1st one is overlain but still visible) and legend is shown (1st one is removed)
3. Deselect 2nd layer -> 1st layer is shown again as expected but the **legend completely vanishes**

Could you please try to fix this?

**Comment by 4lm** [comment]
Hi @nesnoj,

right now, the logic is, that if you are switching on a choropleth map on, any other legend of any other active choropleth map is removed. Yes, you're right, that's not a nice behavior and should be fixed. I think there is an easier and a harder way.

1. Easier: only one choropleth map at once is allowed. If the user clicks on one choropleth map an previous active choropleth map will be deactivated and the toggle switch of that choropleth map switches itself to off. This approach could be feasible as long as all choropleth maps cover the whole region and are relatively opaque, so that it makes sense (or at least is OK) to have only one choropleth map shown at the time.

2. Harder: Imagine, we have multiple switches switched on. The legend of the last activated switch is always shown. Now we switch the last switched on choropleth map, off, then the legend of the active choropleth map with the highest order is shown. The highest order could be numerical and determined by the vertical order of the switches in the config file - assigned via a counter in the __init__ function(s) of the concerning class(es) in forms.py.

I also thought about implementing a click history of the activated choropleth maps in which the legend is reactivated in the order the switches are toggled on, but this would totally confuse the user, if the toggles are switched on and off in an unordered fashion.

What do you think?

**Comment by nesnoj** [comment]
Thanks for the detailed answer, I think the first, easy solution is appropriate.
As the other open tasks are way more important, I propose to leave it for now and create a fix around mid of March..

**Comment by nesnoj** [comment]
Fixed by #20
