### ISSUE TITLE
Results layers after reload enabled and not visible

### ISSUE THREAD

**Issue by 4lm** [rl-institut/WAM_APP_stemp_abw#43]
How to reproduce:

- Hit simulate
- Reload page
- Go to result layers, click on a switch

If your layers are gone (above steps) and you hit simulate:

- runs endless, if you enabled at least one switch
- works, if all switches are enabled and layers are back again

**Comment by nesnoj** [comment]
I'll check if this is related to the session data which may survive the refresh..

**Comment by nesnoj** [comment]
Fixed in f574f31a07752176b499124e736d24836abf60d0.

The session is re-created on page reload. This resets all settings on reload but will keep the frontend settings in line with the session settings.

Until the [WAM PR](https://github.com/rl-institut/WAM/pull/57) is merged you need to checkout WAM branch[`features/allow-force-new-session`](https://github.com/rl-institut/WAM/tree/features/allow-force-new-session) to make it work.

**Comment by nesnoj** [comment]
I found a better way: Instead of forcing a new session the session data are re-initialized (deleted) which allows parallel usage of WAM apps without destroying the session, cf. https://github.com/rl-institut/WAM/pull/57

I merged the solution into `feature/layers-in-results` so there's **no need** to use a special WAM branch! (will delete it)
