### ISSUE TITLE
Tooltip triangle is broken

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM_APP_stemp_abw#60]
I defined the tooltips to popup to the right in the attribute `data-position="right"` ([example](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/20dd5823fd17e9063106003112b469e76fcee5c0/templates/stemp_abw/map.html#L63)). Even defined in such a way, when there's not enough space they pop up upwards which leads to a broken triangle.

Example:
![stemp_abw_tooltip_triangle](https://user-images.githubusercontent.com/15910173/60008829-0b833900-9675-11e9-88a2-804bef35f945.png)
(same happens in the last layers of a layer list)

**Comment by 4lm** [comment]
OK, will have a look!

**Comment by 4lm** [comment]
This one was interesting. This effect took place only if there was not enough space for the tooltip in the ordered direction. Solution, don't force the unenforceable, let the tooltip appear to the left!

For this:

- I changed the area of the tooltip to the whole button (took me a few minutes to realize, that there was a tooltip behind the tiny arrow icon inside the button :smile:).
- let the tooltip appear to the left of the button (without the whole button as a tooltip area, the tooltip would overlay the word "Simulation", to the left of the tiny arrow icon - a real 2 for 1)
- change the cursor of the button to pointer, because first and foremost it's a button to click!

![image](https://user-images.githubusercontent.com/3404313/61387537-9c38e780-a8b6-11e9-8560-04ca4703d04c.png)

@nesnoj. What do you think?

**Comment by nesnoj** [comment]
Done in #69, thx @4lm!
