### ISSUE TITLE
Data shipping & deployment

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM_APP_stemp_abw#71]
Find a good and user-friendly way to ship & deploy tool data, e.g. using [django's fixtures](https://docs.djangoproject.com/en/2.2/howto/initial-data/). Make sure it's compatible with the WAM.

**Comment by 4lm** [comment]
Yes, will have a look now!

**Comment by 4lm** [comment]
Hi @nesnoj,

I checked the data handling via fixtures out and it works like a charm!

Unfortunately it's a little bit more complex than that :wink:

But one thing after another:

### Fixtures

- Work like a charm (dumping and restoring)! They are a little bit slow, but workable. In the case of stemp_abw it's 1 minute for backup and 8 minutes for restore. You can backup and restore the whole project, only specific apps (like stemp_abw) or specific tables. Everything we need is there!

- JSON fixtures are half the size of XML fixtures and ~ twice as fast. The size of a JSON fixture for stemp_abw is around 130 MB (indented) and 115 MB (as one line).

- Compressed via gzip, fixture size is around 16 MB for stemp_abw, which is ~ the size of the Postgres binary dump in pgAdmin.

### Git/GitHub

- Git always tracks line for line, so only indented JSON or XML files would make sense to track in Git.

- Unfortunately, GitHub only allows file sizes not exceeding 100 MB. We are over this limit.

We have now two possibilities on GitHub:

- Use Git LFS, which is made to handle larger files. Unfortunately it costs money if you exceed GitHub LFS storage or monthly traffic over 1 GB. I you exceed and don't pay, the LFS functionality in your repo will be disabled, the rest of the repo will work.

- Gzip the fixtures and add them as assets to a Github release. The user would than have to unzip them and put them in the right folder "fixtures/". A litte installation instruction would be necessary and no tracking of the fixtures in the Git repo itself.

### Stumbling Stones

Right now it's not possible to restore the fixtures on a fresh install of the project, because in the code base there are hard coded references to tables in the database, which makes the installation via migrations fail.

I had to butcher the the code base to make the migrations work:

In `forms.py`:

- Line: 45 - 101, comment out \_\_init\_\_ method
- Line: 161 - 166, comment out \_\_init\_\_ method

In `config/prepare_context.py`:

- Line: 89 - 155,  comment out function body, empty dict is returned

In `dataio/load_static.py`:

- Line: 16 - 39, comment out function body, empty dict is returned
- Line: 47 - 51, comment out function body, alter return statement to "return pd.DataFrame()"

After the migration and the data restore of stemp_abw via a fixture I reverted above changes. Everything works, no problem. But I think this is way to complicated for a normal user ...

And to decouple the above mentioned code for migrations to work, seems not easy - maybe you can have a look at it ...

What do you think?

**Comment by 4lm** [comment]
> We have now two possibilities on GitHub:
> 
> Use Git LFS, ...
> 
> Gzip the fixtures and ...

@nesnoj, I think there is also a third possibility. Add the fixtures as zip files (~ 16 MB) to the Git repo. Maybe with the help of a litte script file, that zips fixtures from and unzips fixtures to the `fixtures/` folder and an .gitignore entry, set to ignore the `fixtures/` folder:

- `fixtures/<fixtures files>` <-- not tracked (.gitignore)
- `fixtures_zipped/<zipped fixtures files` <-- tracked in git repo

Handling:

- `python manage.py (zip-fixtures|unzip-fixtures)` <-- via [Django custom management commands](https://www.pythoncircle.com/post/48/how-to-create-management-commands-in-django/)

**Comment by nesnoj** [comment]
Sounds good! I'd prefer to have the fixtures stored on [zenodo](https://zenodo.org/) to avoid bloating the repo. Let me know if you want me to upload something. 
A bash script could wget, unzip and copy the files to the desired dir (a python script might be better for windows' sake?)

> * `python manage.py (zip-fixtures|unzip-fixtures)` <-- via [Django custom management commands](https://www.pythoncircle.com/post/48/how-to-create-management-commands-in-django/)

As mentioned, I guess that custom management commands are only available on Project (WAM) level?! Alternatively, a script should do the job..

> Right now it's not possible to restore the fixtures on a fresh install of the project, because in the code base there are hard coded references to tables in the database, which makes the installation via migrations fail.

Were you able to overcome this problem?
I have similar problems when I change a model definition and used the same workaround (comment out all usages of QuerySets). ([source](https://stackoverflow.com/questions/33681952/django-migration-error-column-does-not-exist))

BTW: In the end, pls add deployment instructions to the [install docs](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/dev/doc/installation_and_setup.rst).

**Comment by 4lm** [comment]
> Sounds good! I'd prefer to have the fixtures stored on zenodo to avoid bloating the repo. Let me know if you want me to upload something.

I also have zenodo account now and can upload the appropriate fixture if we fixed the general install problem (also see last answer).

>As mentioned, I guess that custom management commands are only available on Project (WAM) level?! Alternatively, a script should do the job..

I had a look and you can add the custom management commands on app level so even if we use them on project level (root folder via pyhton manage.py ...) IMO we should be able to make this work on the appropriate app level.

> Were you able to overcome this problem?

No, IMO this needs a bigger refactoring round.

**Comment by nesnoj** [comment]
> I also have zenodo account now and can upload the appropriate fixture if we fixed the general install problem

For the final version, I'd like to upload the data using RLI's zenodo account

> I had a look and you can add the custom management commands on app level 

Good news, go ahead! :)

> No, IMO this needs a bigger refactoring round.

The problem seems to occur if one intends to alter the models/DB tables but the requested models are accessed during initialization (which happens in the parts you mentioned), e.g. `<model>.objects.all()`.
To solve this, we could make use of
1. exception handling as suggested [here](https://stackoverflow.com/a/53227188/6419458) but it should be more specific to avoid ignoring other errors that might occur, something like
```
try:
    foo = Model.objects.all()
except <ModelDoesNotExistError>:
    pass
```
(ModelDoesNotExistError is fictional) What was the exact error message you got? [OperationalError](https://docs.djangoproject.com/en/2.2/ref/exceptions/#database-exceptions)? I guess [DoesNotExist](https://docs.djangoproject.com/en/2.2/ref/models/instances/#django.db.models.Model.DoesNotExist) could be the one we're looking for ([example usage](https://www.reddit.com/r/django/comments/6plqbn/advice_to_get_single_object_using_get_or/)).

2. cleaner: check if the model exists in the DB before access (no idea now to do that)
3. wrap model queries into callables to avoid execution on app init ([example](https://stackoverflow.com/a/39084645/6419458))

What do you think?

**Comment by 4lm** [comment]
> For the final version, I'd like to upload the data using RLI's zenodo account

OK.

> Good news, go ahead! :)

:+1: 

> 1. exception handling as suggested here but it should be more specific to avoid ignoring other errors
> 2. cleaner: check if the model exists in the DB before access (no idea now to do that)
> 3. wrap model queries into callables to avoid execution on app init (example)

I like solution (3.) That's pretty much what I did for the i18n part where I wanted to use our given cfg files. Maybe in combination with solution (1.), where exception handling makes sense.

**Comment by nesnoj** [comment]
#77 looks good :+1:, I'll leave it open until you have finished the docs and a trial run (full install from scratch) has taken place..

**Comment by nesnoj** [comment]
Reminder for me: Ship meta tables too as they contain the sources.
